# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'evaluate.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(588, 572)
        Dialog.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Dialog.setFont(font)
        Dialog.setStyleSheet("background-color:rgb(212, 212, 212)")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("")
        self.label_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.c1 = QtWidgets.QComboBox(Dialog)
        self.c1.setMinimumSize(QtCore.QSize(0, 0))
        self.c1.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.c1.setFont(font)
        self.c1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.c1.setStyleSheet("background-color:\"white\"")
        self.c1.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.c1.setObjectName("c1")
        self.c1.addItem("")

        import sqlite3
        myteam=sqlite3.connect('cricket.db')
        curteam=myteam.cursor()
        curteam.execute("select name from teams;")
        try:
            team=curteam.fetchall()
            for nm in team:
                 self.c1.addItem(nm[0])
        except:
           myteam.rollback()

           
        self.horizontalLayout_3.addWidget(self.c1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.c2 = QtWidgets.QComboBox(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.c2.setFont(font)
        self.c2.setStyleSheet("background-color:\"white\"")
        self.c2.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.c2.setObjectName("c2")
        self.c2.addItem("")
        self.c2.addItem("")
        self.c2.addItem("")
        self.c2.addItem("")
        self.c2.addItem("")
        self.c2.addItem("")
        self.horizontalLayout_3.addWidget(self.c2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setMinimumSize(QtCore.QSize(237, 0))
        self.label_2.setBaseSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setObjectName("widget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.t1 = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.t1.setFont(font)
        self.t1.setStyleSheet("background-color:\"white\"")
        self.t1.setText("")
        self.t1.setObjectName("t1")
        self.horizontalLayout_6.addWidget(self.t1)
        self.horizontalLayout_2.addWidget(self.widget)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.l1 = QtWidgets.QListWidget(Dialog)
        self.l1.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.l1.setFont(font)
        self.l1.setStyleSheet("background-color:\"white\"")
        self.l1.setObjectName("l1")
        self.horizontalLayout.addWidget(self.l1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.l2 = QtWidgets.QListWidget(Dialog)
        self.l2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.l2.setFont(font)
        self.l2.setStyleSheet("background-color:\"white\"")
        self.l2.setObjectName("l2")
        self.horizontalLayout.addWidget(self.l2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem9)
        self.p1 = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.p1.setFont(font)
        self.p1.setStyleSheet("color:\"Black\"")
        self.p1.setObjectName("p1")
        self.horizontalLayout_5.addWidget(self.p1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem10)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.p1.clicked.connect(self.evaluate)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "Evaluate The Performance Of Your Fantacy Teams"))
        self.c1.setCurrentText(_translate("Dialog", "Select Team"))
        self.c1.setItemText(0, _translate("Dialog", "Select Team"))
        self.c2.setItemText(0, _translate("Dialog", "Select Match"))
        self.c2.setItemText(1, _translate("Dialog", "match1"))
        self.c2.setItemText(2, _translate("Dialog", "match2"))
        self.c2.setItemText(3, _translate("Dialog", "match3"))
        self.c2.setItemText(4, _translate("Dialog", "match4"))
        self.c2.setItemText(5, _translate("Dialog", "match5"))
        self.label_2.setText(_translate("Dialog", "Players"))
        self.label.setText(_translate("Dialog", "Points"))
        self.p1.setText(_translate("Dialog", "CalculateScore"))

    def evaluate(self):
        team=self.c1.currentText()

        match=self.c2.currentText()

        if team=="Select Team" :
            self.warn("Please select the team!!!")
            return

        if match=="Select Match" :
            self.warn("Please select the match!!!")
            return


        self.l1.clear()
        self.l2.clear()
        import sqlite3
        myteam=sqlite3.connect('cricket.db')
        curteam=myteam.cursor()
        curteam.execute("select players from teams where name=='"+team+"';")
        plrs=curteam.fetchone()
        self.l1.addItems(plrs[0].split(','))
        match=self.c2.currentText()
        score=0
        for i in range(0,11,1):
            total=0
            batscore=0
            bowlscore=0
            fieldscore=0
            strirate=0
            ecorate=0
            player=self.l1.item(i).text()
            myteam=sqlite3.connect('cricket.db')
            curteam=myteam.cursor()
            curteam.execute("select * from '"+match+"' where player=='"+player+"';")
            stats=curteam.fetchone()
            stats=list(stats)
            batscore=int(stats[1]/2)
            if stats[1]>=50:
                batscore+=5
            if stats[1]>=100:
                batscore+=10
            if stats[1]==0 or stats[2]==0:
                strirate=0
            else :
              stirate=stats[1]/stats[2]
            if strirate>=80 and strirate<100:
                batscore+=2
            if strirate>=100:
                batscore+=4
            batscore+=stats[3]
            batscore+=stats[4]*2

            bowlscore=stats[8]*10
            if stats[8]>=3:
                bowlscore+=5
            if stats[8]>=5:
                bowlscore+=10
 
            if stats[7]==0 or stats[5]==0:
               ecorate=0
            else:
                ecorate=6*(stats[7]/stats[5])
            if ecorate>=3.5 and ecorate<4.5:
                bowlscore+=4
            if ecorate>=2 and ecorate<3.5:
                bowlscore+=7
            if ecorate<2:
                bowlscore+=10
            
            fieldscore=(stats[9]+stats[10]+stats[11])*10
            total=batscore+bowlscore+fieldscore
            self.l2.addItem(str(total))
            score+=total
        self.t1.setText(str(score))

    def warn(self,msg):
        Dialog=QtWidgets.QMessageBox()
        Dialog.setText(msg)
        Dialog.setWindowTitle("Message")
        ret=Dialog.exec()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
